providers = ["dotnet"]

[build]
base = "mcr.microsoft.com/dotnet/aspnet:8.0"

[phases.build]
cmds = ["dotnet publish CafeWebsite.csproj -c Release -o out --no-restore"]

[phases.start]
cmd = "dotnet ./out/CafeWebsite.dll"
